### ISSUE TITLE
Tighten analysis settings

### ISSUE THREAD

**Issue by laike9m** [ditman/google_sign_in_as_googleapis_auth#9]
![1](https://user-images.githubusercontent.com/2592205/83910503-8b3bd380-a71f-11ea-9341-d43e5b4b8c25.png)

As discussed in Google chat 🙂

**Comment by ditman** [comment]
You're right, this package is *depending* on `pedantic`, but it's NOT USING IT!

🤦‍♂️

Thanks for reporting!
